### ISSUE TITLE
Add "transitionally reserved" country codes from source

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/IATI-Codelists-NonEmbedded#18]
There are lots of withdrawn country codes in the ISO-3166 source.

See the table on this page:
https://www.iso.org/obp/ui#iso:pub:PUB500001:en

There are four types of "reserved" code. Would be good to determine which ones we’re interested in:

 * Exceptionally reserved code elements (yellow) (e.g. [UK](https://www.iso.org/obp/ui#iso:code:3166:UK))
 * Transitionally reserved code elements (grey) (e.g. [AN](https://www.iso.org/obp/ui#iso:code:3166:AN))
 * Indeterminately reserved code elements (red) (e.g. [RL](https://www.iso.org/obp/ui#iso:code:3166:RL))
 * Formerly assigned code elements (pink) (e.g. [HV](https://www.iso.org/obp/ui#iso:code:3166:HVBF))

**Comment by andylolz** [comment]
What do you think, @markbrough?

**Comment by markbrough** [comment]
Hmm. Tricky! I agree we should make a decision on this though!

I would say yes to:
* Transitionally reserved codes -- as they were used until very recently so are definitely likely to be useful.

I would say no to:
* Exceptionally reserved codes -- as don't really look like countries (or there is already a code already assigned to them, e.g. UK)
* Indeterminately reserved codes -- these are either not countries or they are car registration codes for countries which already have an official ISO country code

I'm not sure about:
* Formerly assigned code elements -- many of these are former colonial names, and I don't think we should be including stuff like that (especially considering many of them had very limited recognition). There are three codes that could potentially be useful: Czechoslovakia, German Democratic Republic, Democratic Yemen were all still in existence into early 1990. So we could potentially include those three but I'm also happy to exclude this whole section.

**Comment by andylolz** [comment]
Thanks @markbrough - really helpful.

On that basis, I'm tempted to just go with transitionally reserved codes for now, and maybe later decide a rule for including formerly assigned codes.

**Comment by markbrough** [comment]
I agree, I think this sounds sensible!

**Comment by andylolz** [comment]
Ace. I've edited the issue title accordingly.

**Comment by andylolz** [comment]
Oops, I updated the title to the wrong thing! Fixed now.
