### ISSUE TITLE
Extract flat files as prep for translation to other languages

### ISSUE THREAD

**Issue by matmaxgeds** [codeforIATI/IATI-Codelists-NonEmbedded#8]
Thinking about what we would need to make it easy to setup for translation so that someone would not need to go through xml files e.g. getting it into an excel sheet with the supporting info, and a column for each language etc

**Comment by andylolz** [comment]
Ahh! @markbrough was also giving this workflow some thought recently.

**Comment by matmaxgeds** [comment]
Translation (esp from your native language to another - as opposed from another to your native one is hard) but I think that given both Mark and I speak some German we should have a crack as a test case. I am also going to ruin it by suggesting that we use auto-internet tools as the first pass....either google translate, or I find:https://www.deepl.com/pro.html#developer much better.

Mainly I think it would be a cool think the CfI could add from the community side to IATI.

**Comment by andylolz** [comment]
So I think Mark’s approach was to scrape the German sector code translations (not sure where from, exactly, except that it was a PDF) and has added them on a branch. See e.g. https://github.com/codeforIATI/IATI-Codelists-NonEmbedded/commit/4a6e9d7d754d28a6ee76adb037cba4409c3139ad

**Comment by matmaxgeds** [comment]
Cool, and I realise that now we have the CSV/XLSX download feature, I can get flat files for myself

**Comment by andylolz** [comment]
Closing this, because I think @markbrough’s work on this now exists over here:
https://github.com/codeforIATI/translate-codelists

**Comment by markbrough** [comment]
Yup! I guess it would maybe also be cool to be able to do this in bulk, i.e. extract translation files for all codelists for a particular language? But I guess it sort of works for now. I've added an issue here anyway: https://github.com/codeforIATI/translate-codelists/issues/3
